model_params:
  dense_units: 512
  freeze_backbone: true
  dropout_rate: 0.5
training_params:
  epochs: 10
  batch_size: 32
  learning_rate: 0.001
  optimizer: adam
  loss_function: binary_crossentropy
metrics:
- accuracy
paths:
  subsets_division_ds_path: ''
  labels_ds_path: ''
